### ISSUE TITLE
iMacros add-on broken. 

### ISSUE THREAD

**Issue by JHPArizona** [MoonchildProductions/Pale-Moon#326]
I have iMacros installed, version 8.8.2.1 which worked fine in Pale Moon 25.8.1 (x86) I have set up a lot of macros to handle repetitive steps. After upgrade to Pale Moon version 26, iMacros does not "Play" and every macro (I tried) produces error 
TypeError: Downloads.getList is not a function (Error code: -1001)

I have tried the macro with and without the XSS filter running. I tried upgrading to the lastest version of iMacros although I had read in another thread that 8.8.2.1 works versus anything higher is broken on version 25.8.1. The new version is 8.8.7.1. This version did not work either. When I get more time, I will try some of the other versions and see if I can make it work. NOTE: This is the free version from the company.

If you want any further testing, just let me know.
**Update 20160129:**
I have downgraded to 25.8.1 as I could not work as efficiently without iMacros. Reconfirm that it works fine in this version.

**Comment by chaoskagami** [comment]
Leaving aside the fact that said addon is proprietary and I don't know how it ticks; I doubt it is working correctly in that version since we don't have an implementation of getList in Downloads.jsm and don't appear to EVER have had one. Firefox refactored Downloads.jsm and added that in the newer versions.

Aside from that; it's probably possible to make a shim for firefox compatibility. getList takes a single argument: Downloads.PUBLIC, Downloads.PRIVATE, or Downloads.ALL and returns the correct list for either normal, private, or both. We have different functions here, but a wrapper would be possible to implement in less than twenty lines.

@wolfbeast, would that kind of shim be accepted for compatibility with firefox? It should only require changes to Downloads.jsm and I can have it done rather quickly. Building it on the other hand is another issue, as well as testing it since both take forever on a dual core and I nuked my build directory to get back disk space.

**Comment by chaoskagami** [comment]
I made a small changeset which partially imports a bit of Mozilla's Downloads.jsm, mostly the getList function, and redirected out our current functions to use what I imported in order not to break anything API-wise. After compiling Pale Moon functions as before this patch (at least on linux, but the changes are non-invasive anyways.)

https://github.com/chaoskagami/Pale-Moon/commit/365d1a116c12dbf997f8bd707bdbde6e524c3165

Submitting PR to master. Kind of code cleanup, and I'll probably want to port the summary stuff later since that also isn't terribly involved. This should avoid this issue, though I refuse to let iMacros touch my computer.

**Comment by wolfbeast** [comment]
Additions to jsms and shims in them for extension compatibility due to Mozilla's arbitrary renaming is fine, really, as long as existing functionality and code isn't touched in any way, shape or form. Importing additional functions that are needed for support is also fine, just make sure you don't inadvertently overload functions or expose private methods to content that shouldn't be exposed.

As for building and testing: You can use a raw (unpackaged) build to test js module and front-end changes without rebuilding the core of the browser. If someone can pack up an $objdir/dist/bin for you as zip or gz, then you can do that - you'll miss some integration modules like the status bar and ruby, but otherwise that will work just fine for extension testing on changed jsms. Do make sure to run it with `purge-caches` as a command-line to remove any cached versions of chrome scripting.

**Comment by chaoskagami** [comment]
I rebuilt and tested way before you even posted. The PR does seem to work fine, although I did have to touch a bit of code (but nothing that should impact what is supported.)

Mozilla specifies that passing in the Downloads.ALL list will always return the same reference, e.g. you can save and use it later. If an addon got a different list every time it called with Downloads.ALL, it wouldn't be quite compatible. I could have made just a wrapper function if that wasn't part of the definition, but I had to do the opposite.

I made getPublicDownloadList and getPrivateDownloadList the wrappers, not getList. That said, there's no UI changes and it's still functionally equivalent. It wasn't possible to make a functionally equivalent shim without changes in this case due to the above.

**Comment by wolfbeast** [comment]
As long as the exposed functions are functionally the same, then what's under the hood in the jsm doesn't matter. I just need to be sure that the previously existing functions still work exactly the same as they used to so no existing functionality gets broken.

So, $10,000 question: is that the case, yay or nay? ;)

**Comment by chaoskagami** [comment]
Yay. Should be functionally identical, despite some changes. Feel free to test.

**Comment by tumpio** [comment]
Here is another addon that is broken after version 26:
https://addons.mozilla.org/en-US/firefox/addon/download-flash-and-video/
https://forum.palemoon.org/viewtopic.php?f=46&t=10849&p=77365

**Comment by tumpio** [comment]
And the previously reported Download Status Bar addon:
https://forum.palemoon.org/viewtopic.php?f=16&t=10861

I also noticed that the developer of the Download Manager (S3) add-on has said that supporting PM is not possible because the Downloads api changes after Firefox 26.

**Comment by JHPArizona** [comment]
All the posting read and most understood :) Bottom line is a fix going to be included at some point? I have tested 26.02 with same result:TypeError: Downloads.getList is not a function (Error code: -1001)
Back to 25.8.1

**Comment by chaoskagami** [comment]
Bottom line; not a fix, mainly a shim. It does some of what Mozilla's API does, but I had to scrap the changes I made in the original PR since A) They didn't work right and B) I'm convinced at this point it isn't possible to have a dual API here.

That said, while it isn't possible to have a dual API, I can make a set of shims that behave similarly enough that only corner cases will fail.

@tumpio - Thanks for all the examples. You have no clue how helpful this was while testing so far. S3 isn't probably ever going to be compatible, and it isn't because of the Downloads API but because it attempts to include multiple JSMs that don't exist in PM. However, I appear to have gotten the 'download flash and video' addon working. Not done with all the shims yet, though.

**Comment by tumpio** [comment]
Another one reported on the forums:
http://forum.palemoon.org/viewtopic.php?f=16&t=11059
https://addons.mozilla.org/en-US/firefox/addon/flash-video-downloader/

Same issue, expecting new downloads.jsm when 26 or above version number.

**Comment by tumpio** [comment]
Maybe this one too, did not check:
http://forum.palemoon.org/viewtopic.php?f=16&t=10835

**Comment by wolfbeast** [comment]
People having problems with these add-ons have to understand that we can only do so much to be compatible with Firefox add-ons without trying to *be* Firefox. Unfortunately there's also only so much time left for Firefox add-ons before Mozilla will drop all of them from the browser in favor of WebExtensions. XUL and bootstrapped are already completely deprecated by them, for starters.

If you can use older versions of said add-ons that don't rely on later Firefox changes, then that would be preferred over using an older browser -- if for nothing else but for security reasons.

**Comment by wolfbeast** [comment]
With some luck, the patch resulting from #369 will also solve this issue. Please report back after 26.1.1 is published to let us know if the extension is working.

**Comment by JHPArizona** [comment]
Thank you for all the hard work in developing Pale Moon and making the add-ons work! I have not done extensive testing yet but certainly will test all the iMacros I have recorded/written. The initial pass is a success. :)

**Comment by wolfbeast** [comment]
Assuming this has been solved. closing.

**Comment by cyxou** [comment]
Hi! I've updated Pale Moon to v27.1.0 and iMacros does not work there at all. No macro can be played there even the demo ones.

**Comment by JustOff** [comment]
It seems [iMacros 8.9.7](https://addons.mozilla.org/en-US/firefox/addon/imacros-for-firefox/versions/8.9.7) works well in Pale Moon 27.1.

**Comment by cyxou** [comment]
@JustOff how did you managed to install it? I get a compatibility problem when I try to install it:

![2017-02-11_12-20-21](https://cloud.githubusercontent.com/assets/5896622/22852769/929d0b10-f054-11e6-9ead-4441a7b2186a.png)

**Comment by JustOff** [comment]
@cyxou via [Moon Tester Tool](https://addons.palemoon.org/extensions/moon-tester-tool/).

**Comment by mattatobin** [comment]
Disabling Compatibility Checks is not a solution that should ever be pushed to end users.

**Comment by cyxou** [comment]
I've unziped the iMacros v8.9.7 xpi file, made some adjustments in the install.rdf file to target Pale Moon browser and packed it back. Now you can install it directly in Pale Moon. Here is the link: https://github.com/getbot/imacros-for-palemoon/releases

**Comment by JustOff** [comment]
@cyxou, you don't have the right to do so, because iMacros license isn't free:

> [You may not reverse engineer, decompile or disassemble the SOFTWARE. IPSWITCH, INC. shall retain title and all ownership rights to the SOFTWARE](https://imacros.net/license-agreement/).

You better remove you repo from github without waiting for complaint.

**Comment by cyxou** [comment]
@JustOff, this license is for their desktop iMacros product. Have you read the license for iMacros for Firefox extension?

**Comment by JustOff** [comment]
@cyxou 

* From AMO: [You are free to use iMacros for Firefox with any of the applications or services offered by Mozilla. All Other Rights Reserved](https://addons.mozilla.org/en-US/firefox/addon/imacros-for-firefox/license/8.9.7).

Actually you even have no right to use it with Pale Moon.

* From sources: [You may not reverse engineer, decompile or disassemble the SOFTWARE](https://github.com/getbot/imacros-for-palemoon/blob/master/src/License-Freeware.txt#L23).

You better follow my advice to not to run into trouble.

**Comment by cyxou** [comment]
@JustOff, now I see you are right. I should better close this repo before they drop me in slavery on a galley)))

**Comment by cyxou** [comment]
@JustOff, thanks!
