### ISSUE TITLE
Debug build fails

### ISSUE THREAD

**Issue by trav90** [MoonchildProductions/Pale-Moon#432]
Debug builds (using -enable-debug) chokes on what appears to be the XSS filter:

```
In file included from ../../dist/include/nsISupportsUtils.h:22:0,
                 from ../../dist/include/nsISupports.h:123,
                 from /home/trava90/src/PaleMoon/pmsrc/js/xpconnect/src/xpcpublic.h:20,
                 from /home/trava90/src/PaleMoon/pmsrc/js/xpconnect/src/xpcprivate.h:87,
                 from /home/trava90/src/PaleMoon/pmsrc/caps/src/nsScriptSecurityManager.cpp:9:
/home/trava90/src/PaleMoon/pmsrc/caps/src/nsScriptSecurityManager.cpp: In static member function ‘static JSBool nsScriptSecurityManager::XSSFilterPermitsJSAction(JSContext*, JSString*)’:
/home/trava90/src/PaleMoon/pmsrc/caps/src/nsScriptSecurityManager.cpp:520:68: error: ‘const JSSecurityCallbacks {aka const struct JSSecurityCallbacks}’ has no member named ‘findObjectPrincipals’
         NS_ASSERTION(!JS_GetSecurityCallbacks(js::GetRuntime(cx))->findObjectPrincipals,
                                                                    ^
../../dist/include/nsDebug.h:82:11: note: in definition of macro ‘NS_ASSERTION’
     if (!(expr)) {                                            \
           ^
/home/trava90/src/PaleMoon/pmsrc/config/rules.mk:1110: recipe for target 'nsScriptSecurityManager.o' failed
make[6]: *** [nsScriptSecurityManager.o] Error 1
```

**Comment by wolfbeast** [comment]
findObjectPrincipals is indeed not defined. I guess this is a porting error - you should be able to safely comment out the assertion.

**Comment by trav90** [comment]
Commenting out the assertion causes this:

```
In file included from ../../../dist/include/mozilla/Util.h:14:0,
                 from ../../../dist/include/mozilla/throw_gcc.h:12,
                 from ../../../dist/stl_wrappers/new:66,
                 from ../../../dist/include/mozilla/mozalloc.h:18,
                 from ../../../dist/stl_wrappers/cstdlib:39,
                 from /usr/include/c++/6.1.1/stdlib.h:36,
                 from ../../../dist/system_wrappers/stdlib.h:3,
                 from /home/trava90/src/PaleMoon/test/pmsrc/xpcom/string/src/nsSubstring.cpp:15:
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct()’:
../../../dist/include/mozilla/Util.h:166:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&)’:
../../../dist/include/mozilla/Util.h:173:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&)’:
../../../dist/include/mozilla/Util.h:180:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&)’:
../../../dist/include/mozilla/Util.h:187:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&)’:
../../../dist/include/mozilla/Util.h:194:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&)’:
../../../dist/include/mozilla/Util.h:201:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&, const T6&)’:
../../../dist/include/mozilla/Util.h:210:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&, const T6&, const T7&)’:
../../../dist/include/mozilla/Util.h:219:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&, const T6&, const T7&, const T8&)’:
../../../dist/include/mozilla/Util.h:228:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&, const T6&, const T7&, const T8&, const T9&)’:
../../../dist/include/mozilla/Util.h:237:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘void mozilla::Maybe<T>::construct(const T1&, const T2&, const T3&, const T4&, const T5&, const T6&, const T7&, const T8&, const T9&, const T10&)’:
../../../dist/include/mozilla/Util.h:246:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(!constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘T* mozilla::Maybe<T>::addr()’:
../../../dist/include/mozilla/Util.h:252:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘T& mozilla::Maybe<T>::ref()’:
../../../dist/include/mozilla/Util.h:257:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(constructed);
       ^
../../../dist/include/mozilla/Util.h: In member function ‘const T& mozilla::Maybe<T>::ref() const’:
../../../dist/include/mozilla/Util.h:262:7: error: ‘::abort’ has not been declared
       MOZ_ASSERT(constructed);
       ^
../../../dist/include/mozilla/Util.h: In function ‘size_t mozilla::PointerRangeSize(T*, T*)’:
../../../dist/include/mozilla/Util.h:291:3: error: ‘::abort’ has not been declared
   MOZ_ASSERT(end >= begin);
   ^
c++ -o nsUTF8UtilsSSE2.o -c -I../../../dist/stl_wrappers -I../../../dist/system_wrappers -include /home/trava90/src/PaleMoon/test/pmsrc/config/gcc_hidden.h -DMOZ_GLUE_IN_PROGRAM -DMOZILLA_INTERNAL_API -DNO_NSPR_10_SUPPORT -D_IMPL_NS_COM  -I/home/trava90/src/PaleMoon/test/pmsrc/xpcom/string/src -I. -I../../../dist/include  -I/home/trava90/src/PaleMoon/test/pmbuild/dist/include/nspr -I/home/trava90/src/PaleMoon/test/pmbuild/dist/include/nss       -fPIC  -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -Wcast-align -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -std=gnu++0x -pthread -pipe  -DDEBUG -D_DEBUG -DTRACING -g -O1 -msse2 -mfpmath=sse -fno-omit-frame-pointer  -msse2   -DMOZILLA_CLIENT -include ../../../mozilla-config.h -MD -MP -MF .deps/nsUTF8UtilsSSE2.o.pp  /home/trava90/src/PaleMoon/test/pmsrc/xpcom/string/src/nsUTF8UtilsSSE2.cpp
/home/trava90/src/PaleMoon/test/pmsrc/config/rules.mk:1110: recipe for target 'nsSubstring.o' failed
```

**Comment by wolfbeast** [comment]
hm.
I'll have to check if it's also a problem on Windows.

**Comment by trav90** [comment]
Disregard above Util.h errors. They are not related to debug builds, but are rather caused by breaking changes made in GCC 6.1.

Commenting out the assertion as mentioned in comment 2 fixes debug builds on Linux with GCC 4.9. I've submitted PR #433 to resolve this.
